const designations = [
  "Accountant",
  "Acting Overseer",
  "Administrative Officer",
  "Ambulance Driver",
  "Assistant Superintendent of Audit",
  "Attendant",
  "Audit Officer",
  "Cardiographer",
  "Cardiologist",
  "Caregiver",
  "Chief Medical Laboratory Technologist",
  "Chief Occupational Therapist",
  "Chief Overseer Special Grade",
  "Chief Public Health Management Assistant",
  "Chief Special Grade Nursing Officer",
  "Chief Special Grade Pharmacist",
  "Consultant Anaesthetist",
  "Consultant Cancer Surgeon",
  "Consultant Cardiologist",
  "Consultant Cardiothoracic Surgeon",
  "Consultant Chemical Pathologist",
  "Consultant Chemical Physician",
  "Consultant Clinical Geneticist",
  "Consultant Clinical Microbiologist",
  "Consultant Clinical Nutrition Physician",
  "Consultant Clinical Oncologist",
  "Consultant Clinical Onwloant",
  "Consultant Dermatologist",
  "Consultant Emergency Physician",
  "Consultant Endocrinologist",
  "Consultant ENT Surgeon",
  "Consultant Eye Surgeon",
  "Consultant Gastroenterologist",
  "Consultant General Surgeon",
  "Consultant Genito Urinary Surgeon",
  "Consultant Hematologists",
  "Consultant Histopathologist",
  "Consultant in Community Dentistry",
  "Consultant Interventional Radiologist",
  "Consultant Mycologist",
  "Consultant Neurologist",
  "Consultant Neurosurgeon",
  "Consultant Nutrition Physician",
  "Consultant Obstetrician and Gynecologist",
  "Consultant Oncologist",
  "Consultant Onco-Surgeon",
  "Consultant Ophthalmologist",
  "Consultant Oral & Maxillofacial Surgeon",
  "Consultant Orthodontist",
  "Consultant Orthopedic Surgeon",
  "Consultant Paediatric Oncologist",
  "Consultant Pediatric Clinical Geneticist",
  "Consultant Pediatric Endocrinologist",
  "Consultant Pediatric Intensivist",
  "Consultant Pediatric Neurology",
  "Consultant Pediatric Surgeon",
  "Consultant Pediatrician",
  "Consultant Physician",
  "Consultant Psychiatrist",
  "Consultant Radiologist",
  "Consultant Resident Physician",
  "Consultant Respiratory Physician",
  "Consultant Surgeon",
  "Consultant Thoracic Surgeon",
  "Consultant Transfusion Physician",
  "Cook",
  "Dental Surgeon",
  "Dental Technician",
  "Dental Technologist",
  "Deputy Director",
  "Development Officer",
  "Diet Stewardess",
  "Director",
  "Dispensing Officer",
  "Driver",
  "EEG Technician",
  "Electroencephalographer",
  "Emergency Physician",
  "ENT Assistant",
  "Generator Operator",
  "Health Assistant",
  "Health Driver",
  "Health Service Aid",
  "Health Service Aid (Junior)",
  "Health Service Aid (Ordinary)",
  "Hospital Secretary",
  "House Warden",
  "I.C.T. Assistant",
  "Intern House Officer",
  "Lab Assistant",
  "Lift Operator",
  "Machine Operator",
  "Medical Laboratory Scientist",
  "Medical Laboratory Technologist",
  "Medical Officer",
  "Nursing Officer",
  "Nursing Sister",
  "Occupational Therapist",
  "Office Employee Service",
  "Ophthalmic Technologist",
  "Orthoptic Technician",
  "Overseer",
  "Perfusionist",
  "Pharmacist",
  "Physiotherapist",
  "Principal",
  "Public Health Inspector",
  "Public Health Management Assistant",
  "Public Health Midwife",
  "Radiation Therapist",
  "Radiographer",
  "Registrar",
  "Seamstress Operator",
  "Senior Hospital Dental Officer",
  "Senior House Officer",
  "Senior Registrar",
  "Sewing Operator",
  "SHO",
  "Special Garde Nursing Officer",
  "Special Grade Midwife",
  "Special Grade Overseer",
  "Speech and Language Therapist",
  "Student Nurse",
  "Superintendent Occupational Therapist",
  "Superintendent of Audit",
  "Superintendent Radiographer",
  "Technical Officer",
  "Telephone Operator",
  "Trainee Cardiographer",
  "Ward Clerk"
];

export const applicationTypes = {
  doctor: {
    key: "doctor",
    title: "Hospital Registration / ID Application",
    description:
      "Complete this institutional registration form for hospital identity card issuance and administrative records.",
    formLabel: "Hospital Doctors",
    headerTitle: "National Hospital of Sri Lanka",
    headerSubtitle: "Hospital Employee Registration & Identity Card Application",
    formCode: "Reference Form: NHSL/ID/REG-2026",
    fields: [
      {
        name: "nameWithInitials",
        label: "Name with Initials",
        labelSubtext: "(මුලකුරු සමඟ නම)",
        type: "text",
        required: true,
        section: "Personal Information",
      },
      {
        name: "nic",
        label: "NIC",
        labelSubtext: "(ජාතික හැඳුනුම්පත් අංකය)",
        type: "text",
        required: true,
        section: "Personal Information",
      },
      {
        name: "gender",
        label: "Gender",
        labelSubtext: "(ස්ත්‍රී / පුරුෂ)",
        type: "select",
        required: true,
        section: "Personal Information",
        options: ["Male", "Female", "Other"],
      },
      {
        name: "age",
        label: "Age",
        labelSubtext: "(වයස)",
        type: "number",
        min: "18",
        required: true,
        section: "Personal Information",
      },
      {
        name: "birthday",
        label: "Date of Birth",
        labelSubtext: "(උපන් දිනය)",
        type: "date",
        required: true,
        section: "Personal Information",
      },
      {
        name: "designation",
        label: "Designation",
        labelSubtext: "(තනතුර)",
        type: "select",
        required: true,
        section: "Employment Information",
        options: designations,
      },
      {
        name: "divisionWard",
        label: "Division / Ward",
        labelSubtext: "(අංශය / වාට්ටුව)",
        type: "text",
        required: true,
        section: "Employment Information",
      },
      {
        name: "employeeNo",
        label: "Employee Number",
        labelSubtext: "(සේවක අංකය)",
        type: "text",
        required: true,
        section: "Employment Information",
      },
      {
        name: "address",
        label: "Address",
        labelSubtext: "(ලිපිනය)",
        type: "textarea",
        rows: 3,
        fullWidth: true,
        required: true,
        section: "Contact Information",
      },
      {
        name: "mobileNumber",
        label: "Mobile Number",
        labelSubtext: "(ජංගම දුරකථන අංකය)",
        type: "tel",
        required: true,
        section: "Contact Information",
      },
      {
        name: "email",
        label: "Email",
        labelSubtext: "(ඊමේල්)",
        type: "email",
        required: true,
        section: "Contact Information",
      },
      {
        name: "signatureFile",
        label: "Holder Signature",
        labelSubtext: "(අයදුම්කරුගේ අත්සන)",
        type: "file",
        accept: "image/*",
        required: false,
        section: "Attachments",
      },
      {
        name: "photoFile",
        label: "Passport-size Photo Upload",
        labelSubtext: "(ගමන් බලපත් ප්‍රමාණයේ ඡායාරූපය)",
        type: "file",
        accept: "image/*",
        required: false,
        section: "Attachments",
      },
      {
        name: "studioPhotoNo",
        label: "Studio Photo No.",
        labelSubtext: "(ස්ටුඩියෝ ඡායාරූප අංකය)",
        type: "text",
        required: false,
        section: "Office Use Only",
      },
      {
        name: "referenceNo",
        label: "Reference No.",
        labelSubtext: "(යොමු අංකය)",
        type: "text",
        required: false,
        section: "Office Use Only",
      },
    ],
  },
  office: {
    key: "office",
    title: "Office Workers Application",
    description:
      "Use this form to apply for office-based roles such as admin, accounts, receptionist, or support staff.",
    formLabel: "Office Workers",
    fields: [
      { name: "fullName", label: "Full Name", type: "text", required: true },
      { name: "email", label: "Email Address", type: "email", required: true },
      { name: "phone", label: "Phone Number", type: "tel", required: true },
      { name: "nic", label: "NIC", type: "text", required: true },
      { name: "companyName", label: "Current / Previous Company", type: "text", required: true },
      { name: "department", label: "Department", type: "text", required: true },
      { name: "position", label: "Applied Position", type: "text", required: true },
      {
        name: "experienceYears",
        label: "Years of Experience",
        type: "number",
        min: "0",
        required: true,
      },
      {
        name: "skills",
        label: "Skills / Tools",
        type: "textarea",
        required: true,
      },
      {
        name: "address",
        label: "Current Address",
        type: "textarea",
        required: true,
      },
    ],
  },
};

export const hospitalFieldConfigExample = {
  name: "fullName",
  label: "Full Name",
  labelSubtext: "(සම්පූර්ණ නම)",
  type: "text",
  required: true,
  section: "Personal Information",
};

export const applicationList = [applicationTypes.doctor, applicationTypes.office];

export const getApplicationByKey = (key) => applicationTypes[key] || null;