export const applicationTypes = {
  doctor: {
    key: "doctor",
    title: "Hospital Registration / ID Application",
    description:
      "Complete this institutional registration form for hospital identity card issuance and administrative records.",
    formLabel: "Hospital Doctors",
    headerTitle: "National Hospital of Sri Lanka",
    headerSubtitle: "Hospital Employee Registration & Identity Card Application",
    formCode: "Reference Form: NHSL/ID/REG-2026",
    fields: [
      {
        name: "referenceNumber",
        label: "Reference Number",
        labelSubtext: "(යොමු අංකය)",
        type: "text",
        required: true,
        section: "Administrative Use",
      },
      {
        name: "employeeNumber",
        label: "Employee Number",
        labelSubtext: "(සේවක අංකය)",
        type: "text",
        required: true,
        section: "Administrative Use",
      },
      {
        name: "fullName",
        label: "Full Name",
        labelSubtext: "(සම්පූර්ණ නම)",
        type: "text",
        required: true,
        section: "Personal Information",
      },
      {
        name: "initials",
        label: "Initials",
        labelSubtext: "(මුල් අකුරු)",
        type: "text",
        required: true,
        section: "Personal Information",
      },
      {
        name: "nic",
        label: "NIC / Passport Number",
        labelSubtext: "(ජා.හැ./ගමන් බලපත් අංකය)",
        type: "text",
        required: true,
        section: "Personal Information",
      },
      {
        name: "gender",
        label: "Gender",
        labelSubtext: "(ස්ත්‍රී / පුරුෂ)",
        type: "select",
        required: true,
        section: "Personal Information",
        options: ["Male", "Female", "Other"],
      },
      {
        name: "age",
        label: "Age",
        labelSubtext: "(වයස)",
        type: "number",
        min: "18",
        required: true,
        section: "Personal Information",
      },
      {
        name: "designation",
        label: "Designation",
        labelSubtext: "(තනතුර)",
        type: "text",
        required: true,
        section: "Employment Information",
      },
      {
        name: "divisionWard",
        label: "Division / Ward",
        labelSubtext: "(අංශය / වාට්ටුව)",
        type: "text",
        required: true,
        section: "Employment Information",
      },
      {
        name: "address",
        label: "Address",
        labelSubtext: "(ලිපිනය)",
        type: "textarea",
        rows: 3,
        fullWidth: true,
        required: true,
        section: "Contact Information",
      },
      {
        name: "mobileNumber",
        label: "Mobile Number",
        labelSubtext: "(ජංගම දුරකථන අංකය)",
        type: "tel",
        required: true,
        section: "Contact Information",
      },
      {
        name: "email",
        label: "Email",
        labelSubtext: "(ඊමේල්)",
        type: "email",
        required: true,
        section: "Contact Information",
      },
      {
        name: "signatureFile",
        label: "Holder Signature",
        labelSubtext: "(අයදුම්කරුගේ අත්සන)",
        type: "file",
        accept: "image/*",
        required: false,
        section: "Attachments",
      },
      {
        name: "signaturePlaceholder",
        label: "Signature Box",
        labelSubtext: "(අත්සන සඳහා වෙන් කළ කොටුව)",
        type: "placeholderBox",
        placeholderText: "HOLDER SIGNATURE",
        required: false,
        section: "Attachments",
      },
      {
        name: "photoFile",
        label: "Passport-size Photo Upload",
        labelSubtext: "(ගමන් බලපත් ප්‍රමාණයේ ඡායාරූපය)",
        type: "file",
        accept: "image/*",
        required: false,
        section: "Attachments",
      },
      {
        name: "photoPlaceholder",
        label: "Passport-size Photo Box",
        labelSubtext: "(ඡායාරූපය සඳහා කොටුව)",
        type: "placeholderBox",
        placeholderText: "PASSPORT SIZE PHOTO",
        required: false,
        section: "Attachments",
      },
    ],
  },
  office: {
    key: "office",
    title: "Office Workers Application",
    description:
      "Use this form to apply for office-based roles such as admin, accounts, receptionist, or support staff.",
    formLabel: "Office Workers",
    fields: [
      { name: "fullName", label: "Full Name", type: "text", required: true },
      { name: "email", label: "Email Address", type: "email", required: true },
      { name: "phone", label: "Phone Number", type: "tel", required: true },
      { name: "nic", label: "NIC / Passport Number", type: "text", required: true },
      { name: "companyName", label: "Current / Previous Company", type: "text", required: true },
      { name: "department", label: "Department", type: "text", required: true },
      { name: "position", label: "Applied Position", type: "text", required: true },
      {
        name: "experienceYears",
        label: "Years of Experience",
        type: "number",
        min: "0",
        required: true,
      },
      {
        name: "skills",
        label: "Skills / Tools",
        type: "textarea",
        required: true,
      },
      {
        name: "address",
        label: "Current Address",
        type: "textarea",
        required: true,
      },
    ],
  },
};

export const hospitalFieldConfigExample = {
  name: "fullName",
  label: "Full Name",
  labelSubtext: "(සම්පූර්ණ නම)",
  type: "text",
  required: true,
  section: "Personal Information",
};

export const applicationList = [applicationTypes.doctor, applicationTypes.office];

export const getApplicationByKey = (key) => applicationTypes[key] || null;